### ISSUE TITLE
Help use this in Vivado 2015.4

### ISSUE THREAD

**Issue by smosanu** [muzafferkal/axi-bfm#1]
Hi! I have Vivado 2015.4, and I managed to do all up to the step:
- * Finally goto zynq_example\zynq_example.srcs\sources_1\ipshared\xilinx.com\processing_system7_bfm_v2_0\xxxxxxxx\hdl

For this step, the directory structure looks different:
$ pwd
/home/userx/workspace/zynq_example/zynq_example.srcs
$ ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
   .
   |-sim_1
   |---imports
   |-----base_zynq_design
   |-sources_1
   |---bd
   |-----base_zynq_design
   |-------hdl
   |-------ip
   |---------base_zynq_design_auto_pc_0
   |---------base_zynq_design_auto_pc_1
   |---------base_zynq_design_axi_bram_ctrl_0_0
   |---------base_zynq_design_axi_gpio_0_0
   |---------base_zynq_design_blk_mem_gen_0_0
   |---------base_zynq_design_processing_system7_0_0
   |---------base_zynq_design_processing_system7_0_axi_periph_0
   |---------base_zynq_design_rst_processing_system7_0_50M_0
   |---------base_zynq_design_xbar_0
   |-------ui
$ find -iname "*system*"
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xci
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_0/base_zynq_design_processing_system7_0_0.xml
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xci
./sources_1/bd/base_zynq_design/ip/base_zynq_design_processing_system7_0_axi_periph_0/base_zynq_design_processing_system7_0_axi_periph_0.xml
./sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0
./sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xml
./sources_1/bd/base_zynq_design/ip/base_zynq_design_rst_processing_system7_0_50M_0/base_zynq_design_rst_processing_system7_0_50M_0.xci
$ find -iname "*hdl*"
./sources_1/bd/base_zynq_design/hdl

Any suggestion I can try to make it work? Thank you!

**Comment by muzafferkal** [comment]
Try adding a zynq bfm IP to your block design. I think that’s what’s missing.

Let me know if that doesn’t get you the bfm sources.

 

-K

**Comment by muzafferkal** [comment]
I'm closing these really old issues.
